// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmMEtYEyt1GTWqcF6ZaWSHb6j5-1gF_vA',
    appId: '1:1003762409882:web:8703c90d8aa9b113009a23',
    messagingSenderId: '1003762409882',
    projectId: 'zoctor-7b59d',
    authDomain: 'zoctor-7b59d.firebaseapp.com',
    storageBucket: 'zoctor-7b59d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADxiJLCAb_0Ta83XmdjkpplLdbZSaEp1g',
    appId: '1:1003762409882:android:0607bba0356a36d3009a23',
    messagingSenderId: '1003762409882',
    projectId: 'zoctor-7b59d',
    storageBucket: 'zoctor-7b59d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBF-DYy8fP81oslz3w3yNdxPO0lMHn89M',
    appId: '1:1003762409882:ios:fb31eea35b308955009a23',
    messagingSenderId: '1003762409882',
    projectId: 'zoctor-7b59d',
    storageBucket: 'zoctor-7b59d.firebasestorage.app',
    iosBundleId: 'com.example.zoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBF-DYy8fP81oslz3w3yNdxPO0lMHn89M',
    appId: '1:1003762409882:ios:fb31eea35b308955009a23',
    messagingSenderId: '1003762409882',
    projectId: 'zoctor-7b59d',
    storageBucket: 'zoctor-7b59d.firebasestorage.app',
    iosBundleId: 'com.example.zoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmMEtYEyt1GTWqcF6ZaWSHb6j5-1gF_vA',
    appId: '1:1003762409882:web:b7a0fcf141b090cf009a23',
    messagingSenderId: '1003762409882',
    projectId: 'zoctor-7b59d',
    authDomain: 'zoctor-7b59d.firebaseapp.com',
    storageBucket: 'zoctor-7b59d.firebasestorage.app',
  );
}
